name: Artemis
options:
  bundleIdPrefix: com.project93
  deploymentTarget:
    iOS: "26.0"
settings:
  SWIFT_VERSION: "6.0"
targets:
  Artemis:
    type: application
    platform: iOS
    sources:
      - Artemis
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.project93.artemis
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_NAME: ArtemisTrack
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 2
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
      INFOPLIST_KEY_UIRequiresFullScreen: YES
      TARGETED_DEVICE_FAMILY: "1"
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: S6C5NWTJNU
    scheme:
      testTargets:
        - ArtemisTests
      gatherCoverageData: true
  ArtemisTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ArtemisTests
    dependencies:
      - target: Artemis
    settings:
      GENERATE_INFOPLIST_FILE: YES
schemes:
  Artemis:
    build:
      targets:
        Artemis: all
        ArtemisTests: [test]
    test:
      targets:
        - ArtemisTests
      gatherCoverageData: true
